In [3]:
import numpy as np # this helps in making it easier to type

In [4]:
# Create an array of numbers
arr = np.array([11,21,43,4,15,67,7])

In [5]:
# Print out the array
print(arr)

[11 21 43  4 15 67  7]


In [6]:
# Add some elements to the array
arr = np.append(arr, [10.123,21.7326372, 124.34,-12,0.1121,-21.3324,-21.3324])
arr

array([ 1.10000000e+01,  2.10000000e+01,  4.30000000e+01,  4.00000000e+00,
        1.50000000e+01,  6.70000000e+01,  7.00000000e+00,  1.01230000e+01,
        2.17326372e+01,  1.24340000e+02, -1.20000000e+01,  1.12100000e-01,
       -2.13324000e+01, -2.13324000e+01])

In [7]:
# Copy the array and display the array has elements of the same type (no floats just int)
newarr = arr.astype(int)
newarr

array([ 11,  21,  43,   4,  15,  67,   7,  10,  21, 124, -12,   0, -21,
       -21])

In [8]:
# Copy the array and display the array has elements of the same type (no int just float)
newarr1 = arr.astype(float)
np.round(newarr1,2)

array([ 1.1000e+01,  2.1000e+01,  4.3000e+01,  4.0000e+00,  1.5000e+01,
        6.7000e+01,  7.0000e+00,  1.0120e+01,  2.1730e+01,  1.2434e+02,
       -1.2000e+01,  1.1000e-01, -2.1330e+01, -2.1330e+01])

In [9]:
print(arr[11])

0.1121


In [10]:
print(arr[-2])

-21.3324


In [11]:
arr.shape

(14,)

In [12]:
arr.size

14

In [13]:
# Order the array in ascending order (smallest to biggest)
arr.sort()
arr

array([-2.13324000e+01, -2.13324000e+01, -1.20000000e+01,  1.12100000e-01,
        4.00000000e+00,  7.00000000e+00,  1.01230000e+01,  1.10000000e+01,
        1.50000000e+01,  2.10000000e+01,  2.17326372e+01,  4.30000000e+01,
        6.70000000e+01,  1.24340000e+02])

In [14]:
# Find the location of the largest element in the array
np.argmax(newarr1)

9

In [15]:
# Find the location of the smallest element in the array
np.argmin(arr)

0

In [16]:
# Find where the element in the argument would go when inserted into a sorted array
np.searchsorted(arr,7)

5

In [17]:
#Multi Dimensional Array

In [18]:
arr1 = np.arange(1,91)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90])

In [19]:
arr1.shape

(90,)

In [20]:
arr2 = np.arange(1,91).reshape(9,10)
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [22]:
arr2.shape

(9, 10)

In [21]:
arr3 = np.arange(1,91).reshape(3,3,10)
arr3

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]],

       [[61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
        [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
        [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]]])

In [23]:
arr3.shape

(3, 3, 10)

In [24]:
arr3 = np.arange(1,91)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90])

In [25]:
arr3 = np.arange(1,91).reshape(10,9)
arr3

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70, 71, 72],
       [73, 74, 75, 76, 77, 78, 79, 80, 81],
       [82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [26]:
arr3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90])

In [27]:
arr3[1:3:2,1]

array([11])

In [ ]:
# stats

In [28]:
# Mean
np.mean(arr3)

45.5

In [29]:
# Median
np.median(arr3)

45.5

In [30]:
from statistics import mode

In [32]:
# Mode
array = np.array([2,5,621,21,3,8,9,7,9,8,7,775,5,8])

In [33]:
vals,counts = np.unique(array, return_counts=True)
vals

array([  2,   3,   5,   7,   8,   9,  21, 621, 775])

In [34]:
counts

array([1, 1, 2, 2, 3, 2, 1, 1, 1])

In [35]:
mode = np.argmax(counts)
mode

4

In [36]:
print(vals[mode])

8


In [37]:
from scipy import stats as st
print(st.mode(array))

ModeResult(mode=array([8]), count=array([3]))


/tmp/ipykernel_15765/1434699331.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print(st.mode(array))


In [38]:
np.median(array)

8.0

In [39]:
np.mean(array)

106.28571428571429

In [40]:
st.mode(array)

/tmp/ipykernel_15765/2309137628.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  st.mode(array)


ModeResult(mode=array([8]), count=array([3]))

In [41]:
np.ptp(array)

773

In [42]:
# Tenth percentile
np.percentile(array, 10)

3.6

In [43]:
# Fourteenth percentile
np.percentile(array, 14)

4.640000000000001

In [46]:
# Q1
np.percentile(array, 25)

5.5

In [45]:
# Q2
np.percentile(array, 50)

8.0

In [44]:
# Q3
np.percentile(array, 75)

9.0

In [48]:
# Percentiles as a list
np.percentile(array, [25,50,75])

array([5.5, 8. , 9. ])

In [49]:
np.quantile(array, 0.1)

3.6

In [50]:
np.quantile(array, 0.14)

4.640000000000001

In [51]:
np.quantile(array, 0.25)

5.5

In [52]:
# Quantile
np.quantile(array, [0.25,0.5,0.75])

array([5.5, 8. , 9. ])

In [ ]:
# Pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
test_table = {
    'Students' : ['Name1', 'Name2', 'Name3'],
    'StudentAlt' : ['NameAlt1','NameAlt2','NameAlt3']
}
test_table

{'Students': ['Name1', 'Name2', 'Name3'],
 'StudentAlt': ['NameAlt1', 'NameAlt2', 'NameAlt3']}

In [3]:
df = pd.DataFrame(test_table)

In [4]:
df

Students StudentAlt
0    Name1   NameAlt1
1    Name2   NameAlt2
2    Name3   NameAlt3

In [5]:
df.insert(2,'RegistrationDate',['2002-28-23','testing','to see if it works'])

In [6]:
df

Students StudentAlt    RegistrationDate
0    Name1   NameAlt1          2002-28-23
1    Name2   NameAlt2             testing
2    Name3   NameAlt3  to see if it works

In [7]:
import datetime
import random

In [8]:
df1 = df.drop(columns = ['RegistrationDate'])

In [9]:
df1

Students StudentAlt
0    Name1   NameAlt1
1    Name2   NameAlt2
2    Name3   NameAlt3

In [1]:
import pandas as pd
import numpy as np
import datetime
import random

In [2]:
acc = np.random.randint(1000000000000000,1111111111999999,50)
card = np.random.randint(1000000000000000,1111111111999999,50)
dates = [np.random.choice(pd.date_range(datetime.datetime(2020,1,1),datetime.datetime(2021,3,31))) for i in range(400)]
money = np.random.randint(-300,72000,300)

In [3]:
dftest= pd.DataFrame({'Acc' : [np.random.choice(acc) for i in range(50)],
    'dates': [np.random.choice(pd.date_range(datetime.datetime(2020,1,1),datetime.datetime(2021,3,31))) for i in range(50)],
    'accountId' : [np.random.choice(acc)for _ in range(50)],
                   'cardNumber': np.random.randint(1000000000000000,1111111111999999,50),
                   'ActivationDate' : [np.random.choice(dates) for i in range(50)],
                   'Income' : [np.random.choice(money)for _ in range(50)]})

In [4]:
dftest

Acc      dates         accountId        cardNumber  \
0   1089073164605702 2020-07-23  1086897067783059  1070577177104083   
1   1089073164605702 2020-08-29  1076012124830483  1084069141709883   
2   1023278422538446 2021-02-18  1047696632068278  1028860640571944   
3   1077833788875453 2020-04-21  1023284015180005  1017719863008276   
4   1022350218788921 2020-06-21  1012926937823961  1037831650840734   
5   1074508811383161 2020-08-02  1074508811383161  1027095801649990   
6   1018328443577196 2020-04-28  1026104649067256  1019048605187334   
7   1008512213218866 2020-11-30  1008512213218866  1078901517405662   
8   1097081014412064 2020-11-18  1057637691962746  1054970227435111   
9   1026104649067256 2020-09-21  1075582117820002  1077551132373560   
10  1048748707055874 2020-03-26  1018328443577196  1080035420126280   
11  1026104649067256 2020-10-17  1038074337088929  1092083111997130   
12  1044729679865847 2020-07-27  1048748707055874  1014433076291758   
13  1047696632068278 2021-01-03  1092856977891272  1025407982746404   
14  1023284015180005 2021-01-31  1077833788875453  1035751941419307   
15  1086897067783059 2020-02-17  1078984856494078  1099452454856616   
16  1050928277091323 2021-01-17  1024409531254123  1039774281564975   
17  1017732799052820 2020-08-05  1083068547768842  1006536726045305   
18  1078984856494078 2020-11-10  1000116683622097  1061126228002365   
19  1033804481935493 2020-05-25  1000116683622097  1107856153096012   
20  1022350218788921 2020-06-18  1008512213218866  1088196182390652   
21  1018328443577196 2020-02-15  1035472427678420  1027255624279383   
22  1083970301762132 2020-03-16  1049988729432906  1081454927522711   
23  1110338770912943 2020-10-28  1044729679865847  1053168312888370   
24  1018328443577196 2021-01-12  1050928277091323  1100984167967607   
25  1008512213218866 2020-12-25  1092856977891272  1102866943596842   
26  1062103670536036 2020-09-23  1050928277091323  1107387749475349   
27  1089150808164289 2020-12-22  1075582117820002  1014293350502986   
28  1083068547768842 2020-07-02  1089786406564500  1037147124470420   
29  1108425190355049 2020-06-23  1089150808164289  1011937759408223   
30  1000394489162775 2020-10-25  1103826359325425  1007063993961434   
31  1077833788875453 2020-04-25  1030843468505149  1013328024531854   
32  1099945889596151 2020-06-14  1092856977891272  1028380110456067   
33  1078984856494078 2020-02-17  1103826359325425  1009217443055756   
34  1009255043263315 2020-10-10  1097081014412064  1102973235256715   
35  1008512213218866 2020-12-24  1110338770912943  1073328720904799   
36  1091667027226529 2020-12-19  1092856977891272  1109915171943767   
37  1103826359325425 2021-03-18  1110338770912943  1016428627272418   
38  1078373029100919 2020-05-23  1089150808164289  1088796535284026   
39  1089073164605702 2020-04-07  1023278422538446  1107726169628383   
40  1077833788875453 2020-05-15  1076012124830483  1002995002575487   
41  1083068547768842 2020-07-28  1022350218788921  1063265271262941   
42  1050928277091323 2020-12-19  1025677414473141  1096802814931121   
43  1048748707055874 2020-04-01  1022350218788921  1005827645162771   
44  1103826359325425 2020-05-28  1098271912545918  1062253486621782   
45  1025677414473141 2021-02-02  1057637691962746  1038238788734192   
46  1074508811383161 2020-11-19  1008512213218866  1019875926359670   
47  1048748707055874 2020-06-02  1045747000511915  1018791744884897   
48  1103826359325425 2020-10-04  1062103670536036  1054659812376049   
49  1045747000511915 2021-01-17  1049568136255527  1107012023932001   

   ActivationDate  Income  
0      2020-04-09   60117  
1      2020-09-11   16913  
2      2020-03-17    6766  
3      2020-07-26   12325  
4      2020-03-28   27502  
5      2020-05-06   33715  
6      2021-02-07   70702  
7      2020-04-08    3514  
8      2021-03-05   48238  
9      2020-05-05   39133  
10     2020-03-03   15864  
11     2020-05-29   38821  
12     2020-12-12   27502  
13 

In [7]:
name = ('Naomi','Christine','Chris','Andile','Siphiwe','Mpho','Itumeleng','Thandanani','Lesego','Luthando','Lebogang','Charmaine','Teballo','Lauren',
        'Lynn','Tebogo','Trevor','Wayne','Paballo','Mark','Nicollette','Angela','Nick','Ben','Warren','Fransisco','Charlotte','Lisette','Annelise',
        'Mariska','Ettiene','Martinus','Jacqueline','Usman','Aisha','Maryam','Yakubu','Taiwo','Emeka','Halima','Ifeoma','Kehinde','Chinyere','Chioma',
        'Wanjiru','Mwangi','Odhiambo','Ochieng','William','Ahmed','Onyango','Felo','Nneka','Abdullahi','Amina','Kemunto','Wambui','Njoroge','Wanjiku',
        'Monica','Lawrence','Caleb','Denise','Dennis','Raphael')
surname = ('Wilson','Barnes','van der Linde','Tomlin','Hemmingway','Horton','Bleecher','Skosana','Ngwenya','Ngcobo','Mothapo','Letsoalo',
           'Kubeka','Dlamini','Sedumedi','Hobbs','Motsepe','Zulu','Van Rooyen','Williams','Pieterson','Moloi','Wu','Vos','De Villiers',
           'De Vos','Viljoen','van den Berg','Otieno','Mohamed','Mwangi','Odhiambo','Maina','Ochieng','Ali','Onyango','Juma','Wambui','Njeri',
           'Kariuki','Akinyi','Achieng','Muthoni','Kimani','Adhiambo','Njuguna','Macharia','Barasa','Cheruiyot','Ibrahim','Musa','Abubakar',
           'Isah','Yakubu','Aminu','Yahaya','Shehu','Okafor','Okeke','Adebayo','Okoro','Okon','Chukwu','Nwachukwu','Nwankwo','Okoye','Ogbonna',
           'Adeyemi','Yunusa','Balogun','Nwafor','Effiong','Amadu','Sanusi','Anyanwu','Danjuma','Ohakwu','Opara','Taiwo','Onuoha','Babatunde') 
# cellnumber = ()
password = ('1','2','3','4','5','6','7','8','9','0','!@#$%^&*()_+><,.;=','aqwsxcderfvbgtyhnmjyukliop')
address = ('1234567890!@#$%^&*()_+><,.;=aqwsxcderfvbgtyhnmjyukliop')
domain = ('@yahoo.com','@gmail.com','@outlook.com','@icloud.com')
# area=('Kibler Park','Rispark','Mayfield park','Aspen Hills nature-estate','Glenvista','Oakdene','Raceview','New Redruth',
# 'Verwoerdpark','Hazel Park','Abmarie','Winford','Tedderfield','Mulbarton','Liefde en vrede','Kenilworth','Roodekop','Palm Ridge',
# 'Albertsdal','Mayberry Park','Southfork','General Alberspark','Mimosa Park','Florentia','Eye of Africa','Elsiehof','Duduza',
# 'Olifantsvlei','South Hills','Welfare Park','Forest hill','Haddon','Towerby','Pennylane','Alrode','Rosettenville','Kwa-Thema',
# 'Union','Roxton','Townsview','Linmeyer','South Crest','Elandspark','Tulisa Park','Steeledale','The Hill','Parkhill Gardens',
# 'Electron','Randhart','Elandsfontien','Albemarie','Alberante','Moffat veiw','Roseacre','Klipriversberg','Regents Park Estate')
province=('Gauteng','Free State')

In [8]:
retail=(
    'Chelino Baby', 'Cardies', 'CNA', 'CUM Books','Exclusive Books','Musica','Cell C','Gadget Candy',
    'MTN','Samsung','Vodacom 4U','weFix','Accessorize','Converse','Earthchild','GenX','Guess Kids',
    'Hugo Boss','Keedo','Kids Emporium','Naartjie Clothing','Dion Wired','hp store','Incredible Connection',
    'Da Vinci Ice Cream','Haagen-Dazs','Krispy Kreme','Lindt','Milky Lane','Sweets From Heaven','Bean Tree',
    'Biltong Box','Bread Ahead','Burger King','Chicken Licken','Cinnabon','Debonairs','Fish Aways','Hero Pies',
    'Hot Dog Café','Kauai','KFC','McDonalds','Mi-Vama','My Diners Express','Romans Pizza','Sausage Saloon',
    'Steers','The Flaming Teppan & Tandoor','Wrap it up Cafe','Babies R Us','Edgars','Game','Hub','Verimark',
    'Woolworths','Action Bowling','Action Karting','be.UP Park','Dodgems Cars','Electric Avenue','Galaxy Bingo',
    'Mr Funtubbles','S.O.C.A – Sport on Court','Snow Wonderland','Ster-Kinekor','XD Theatre Dark Ride','Nu Metro',
    'Execuspecs','Specsavers','Sunglass Hut','Aca Joe','Ackermans','Armani Exchange','Bogart Man','Cotton On',
    'Country Road','Diesel Emporium','Exact','Donna','Fabiani','Factorie','Fashion Fusion','Forever New','Foschini',
    'Guess','H&M','Hilton Weiner','Identity','Jet','John Craig','Kingsmead Shoes','Lacoste','Legit','Levis',
    'Miladys','Mr Price Apparell','Old Khaki','Pick n Pay Clothing','Poetry','Polo','Pringle of Scotland','PUMA',
    'Queenspark','Refinery','Replay','Rockport','Sissy Boy','Soviet','Superdry','Tommy Hilfiger','Truworths','YDE',
    'Uzzi','Vans','Zara','Typo','Zoggy’s Tabacconist Store','Aldo','Brazilia Designer Shoe Outlet','Crocs',
    'Europa Art','Green Cross','Havaianas','Shoe City','Skechers','Shoeperama','Spitz','Steve Madden','Superga',
    'Topshelf','Tread + Miller','Boardmans','Essops Home','Home Etc.','Hyper House & Home','Mr Price Home',
    'Rugs Original','Sheet Street','Virgin Active','Sports and Fitness Centre','S.W.E.A.T','Arthur Ford','Clicks',
    'Calypso Hair & Beauty','Dis-Chem','Gerald Wells','Kryolan','L’Occitane','Red Square','Dream Nails','Sorbet',
    'The Body Shop','The Original Barber','XTreme Nutrition','DNA Therapy','Fragrance Boutique','M.A.C',
    'Road Lodge Hotel','Holiday Inn','Afrokwazi','American Swiss','Arthur Kaplan','Bellagio','Browns The Diamond Store',
    'Fossil','Golden Jewellers','Guess Accessories','Lovisa','Mont Blanc','NWJ','Sterns','Swarovski','Swatch',
    'Tag Heuer','Adega','Barcelos Flame Grilled Chicken','Burger Rack','Cacao Chocolate Bar','Calistos',
    'Cape Town Fish Market','Chateau Gateaux Patisserie','Col’cacchio','Cuba Lounge','Cubana','Dros Family Restaurant',
    'Galitos','Jimmys Killer Prawns','John Dorys','Mimmos','Mochachos','Mugg & Bean','Nandos','Panarottis',
    'Primi','RocoMamas','Simply Asia','Starbucks','Tashas','Wimpy','Xpresso','Absolute Pets','Auto Car Express',
    'Cobblers Heel & Key','Security Hyperstore','Fidelity ADT','National Security','Blades & Triggers',
    'Cajees','Cool Collectables','Electric Eye Tattoos','Elna Home Products','Game Liquor','Pick n Pay Liquor',
    'Rare Earth Crystals','Nespresso','Spice Emporium','Reach for A dream Foundation','The Crazy Store','The Scoin Shop',
    'The Vape Shop','Twisp','Cape Union Mart','Crossover','Le Coq Sportif','Mr Price Sport','Quicksilver','Sportscene',
    'Sportsmans Warehouse','The Cross Trainer','Totalsports','Under Armour','Checkers Hyper','Superspar','Tops Liquors',
    'Pick n Pay','Flight Centre','Pentravel','Metrobus','Putco','Wonga','Cash Crusaders Pay Day Advance','Addide Supermarket',
    'Ajayi Supermarkets','Best Choice Supermarket','Bimta Supermarkets','Genesis Supermarkets','Homebiz Supermarkets',
    'Jara Superstore','Prince Ebeano Supermarkets','TwinsFaja Supermarkets','Wetin dey Stores','Blenco supermarkets',
    "Chanrai's Supermarket & Departmental Store",'Eastmatt Supermarkets','Maathai Supermarkets',"Khetia's Supermarkets",
    'Naivas Limited','Mobius Motors','Uchumi Supermarkets','Rea Vipingo Sisal Estate','Lacoste Boutique','De-Paragon Collections',
    'Netz','Abari Bamboo Sunglasses','Yesidefashionstore.com','Laredo Super Store','Naijabuynsell','Bakan Gizo Pharmacy & Stores',
    'Svengali Designs','Fredwud Advanced Furniture','Meridien View Nigeria','Jovic Furniture','Fedsons Group','Vava Furniture'
       )
trancat=('POSPurchase','FeesAndInterest','AccountCredit')
ttype=('CREDIT', 'DEBIT','REWARDS')
area=('Benoni','Boksburg','Brakpan','Carletonville','Germiston','Johannesburg','Krugersdorp','Pretoria','Randburg',
'Randfontein','Roodepoort','Soweto','Springs','Vanderbijlpark','Vereeniging','Alexandra','Lenasia','Midrand','Sandton',
'Mshengu','Klipfontienview','Orange Farm','Alberton','Germiston','Clayville','Daveyton','Devon','Duduza','Edenvale',
'Ennerdale','Impumelelo','Isando','Katlehong','Kempton Park','KwaThema','Nigel','Olifantsfontein','Reiger Park',
'Tembisa','Thokoza','Tsakane','Vosloorus','Wattville','Atteridgeville','Bronberg','Bronkhorstspruit','Centurion',
'Cullinan','Ekangala','Ga-Rankuwa','Hammanskraal','Irene','Mabopane','Mamelodi','Rayton','Refilwe','Soshanguve',
'Zithobeni','Boipatong','Bophelong','Evaton','Sebokeng','Sharpeville','Meyerton','Carletonville','Khutsong',
'Fochville','Kokosi','Greenspark','Wedela','Welverdiend','Blybank','Kagiso','Krugersdorp', 'Kabarak Estate',
'Lekki','Ojota','Victoria Island','Otukpo','Alagbado','Yaba','Ogba','Asokoro','Nicon Town','Ibara','Kamukunji Estate',
'Alimosho','Okota','Gwarrinpa','Ikoyi','Arochukwu','Katagum','Dikwa','Portharcourt','Karen','Langata','Kyuna',
'Enugu','Nsukka','Gombe','Kaduna','Emaa','Banana Island Ikoyi','Maitama','Jabi','Alalubosa','Gigiri','Kilimani',
'Runda','Kitisuru','Kyuna','Lower Kabete','Kileleshwa','Muthaiga','Gigiri','Bahati Estate','Bamburi Estate',
'Mombasa Island','Nakuru','Kisumu','Eldoret','Konza City','Tatu City','Nakuru','Migosi Estate','Milimani Estate',)

In [9]:
Accdf =  pd.DataFrame({'Name' : [random.choice(name)for _ in range(50)],
                   'Surname' : [random.choice(surname)for _ in range(50)],
                   'City': [random.choice(area)for _ in range(50)],
                   'accountId' : [np.random.choice(acc)for _ in range(50)],
                   'cardNumber': np.random.randint(1000000000000000,1111111111999999,50),
                   'ActivationDate' : [np.random.choice(dates) for i in range(50)],
                   'Income' : [np.random.choice(money)for _ in range(50)]})
Accdf

Name     Surname                 City         accountId  \
0      Onyango     Kariuki              Midrand  1000394489162775   
1         Felo     Motsepe            Zithobeni  1103826359325425   
2    Fransisco      Akinyi          Krugersdorp  1083970301762132   
3      Raphael      Wilson               Otukpo  1000116683622097   
4         Felo     Viljoen              Lenasia  1012926937823961   
5        Emeka         Vos        Bahati Estate  1022350218788921   
6        Caleb    Williams             KwaThema  1110338770912943   
7    Charlotte        Musa            Tatu City  1077833788875453   
8       Andile      Yahaya          Welverdiend  1017732799052820   
9       Mwangi      Tomlin  Banana Island Ikoyi  1076012124830483   
10     Wanjiru     Ogbonna         Hammanskraal  1024409531254123   
11     Wanjiru     Danjuma            Clayville  1075582117820002   
12      Trevor        Juma              Blybank  1024409531254123   
13     Ochieng     Viljoen      Olifantsfontein  1049988729432906   
14     Wanjiru     Ochieng         Kempton Park  1045747000511915   
15  Nicollette     Njuguna             Pretoria  1024056144101260   
16     Kehinde       Amadu               Nsukka  1050928277091323   
17    Martinus      Yunusa            Gwarrinpa  1078373029100919   
18     Ochieng     Danjuma             Daveyton  1050928277091323   
19      Mwangi   Nwachukwu              Tsakane  1091179819251211   
20     Mariska     Motsepe          Orange Farm  1077833788875453   
21       Usman       Moloi                Devon  1049988729432906   
22      Tebogo      Tomlin                Kyuna  1074508811383161   
23       Amina       Opara               Kagiso  1077833788875453   
24      Andile      Tomlin               Otukpo  1026104649067256   
25       Ahmed      Onuoha        Carletonville  1075582117820002   
26   Christine      Chukwu               Kokosi  1049568136255527   
27       Ahmed     Achieng       Bamburi Estate  1099945889596151   
28      Chioma         Vos             Alberton  1033804481935493   
29      Trevor    Adhiambo         Kempton Park  1025677414473141   
30  Thandanani  Hemmingway                Karen  1098271912545918   
31       Caleb         Vos                Devon  1091179819251211   
32      Warren      Kubeka              Asokoro  1012926937823961   
33      Mwangi       Aminu      Victoria Island  1045747000511915   
34       Nneka    Odhiambo            Fochville  1103826359325425   
35    Odhiambo      Wambui       Bamburi Estate  1074508811383161   
36      Tebogo      Yunusa            Vosloorus  1008512213218866   
37       Nneka      Akinyi       Bamburi Estate  1033804481935493   
38      Tebogo     Ochieng       Kabarak Estate  1077833788875453   
39     Mariska  Van Rooyen      Klipfontienview  1057637691962746   
40       Emeka        Zulu                 Ogba  1048748707055874   
41     William     Balogun              Asokoro  1078373029100919   
42      Halima      De Vos               Rayton  1091667027226529   
43    Lebogang       Shehu              Mshengu  1098271912545918   
44     Ettiene     Nwankwo      Olifantsfontein  1075582117820002   
45       Caleb       Okeke                Gombe  1035472427678420   
46       Caleb       Okoro        Carletonville  1023284015180005   
47    Martinus    Macharia             Alagbado  1044729679865847   
48   Charmaine       Okoye             Pretoria  1091667027226529   
49       Emeka      Wilson                Dikwa  1089073164605702   

          cardNumber ActivationDate  Income  
0   1040181015519329     2020-12-27   49326  
1   1057002793094764     2020-04-18   49457  
2   1099635005048657     2021-03-22   14042  
3   1100229865490051     2020-12-24   27502  
4   1003073131310903     2020-02-04    1321  
5   1016781174818565     2020-08-03    7727  
6   1106212950923112     2020-08-01   38653  
7   1107367759717748     2020-02-02   24444  
8   1002635970837625     2020-06-25   23866  
9   1008557162044771     2020-

In [10]:
for i in range(6):
  Accdf = Accdf.append(Accdf,ignore_index=True)
Accdf

/tmp/ipykernel_8294/545952476.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Accdf = Accdf.append(Accdf,ignore_index=True)


Name   Surname           City         accountId        cardNumber  \
0       Onyango   Kariuki        Midrand  1000394489162775  1040181015519329   
1          Felo   Motsepe      Zithobeni  1103826359325425  1057002793094764   
2     Fransisco    Akinyi    Krugersdorp  1083970301762132  1099635005048657   
3       Raphael    Wilson         Otukpo  1000116683622097  1100229865490051   
4          Felo   Viljoen        Lenasia  1012926937823961  1003073131310903   
...         ...       ...            ...               ...               ...   
3195      Caleb     Okeke          Gombe  1035472427678420  1092492790915671   
3196      Caleb     Okoro  Carletonville  1023284015180005  1062922367682775   
3197   Martinus  Macharia       Alagbado  1044729679865847  1019174574405382   
3198  Charmaine     Okoye       Pretoria  1091667027226529  1086746092412681   
3199      Emeka    Wilson          Dikwa  1089073164605702  1101171287917984   

     ActivationDate  Income  
0        2020-12-27   49326  
1        2020-04-18   49457  
2        2021-03-22   14042  
3        2020-12-24   27502  
4        2020-02-04    1321  
...             ...     ...  
3195     2020-12-08   12325  
3196     2021-01-21   22084  
3197     2021-02-07   59696  
3198     2020-07-30   55326  
3199     2020-08-08   27797  

[3200 rows x 7 columns]

In [11]:
transactdates = [np.random.choice(pd.date_range(datetime.datetime(2020,4,1,0),datetime.datetime(2021,3,31,0))) for i in range(366)]
transactdf = pd.DataFrame({'Transaction_Description' : [random.choice(retail)for _ in range(3200)],
                   'Transaction_Date' : [np.random.choice(transactdates) for i in range(3200)],
                   'Amount' : np.random.randint(1,6000,3200)})
transactdf.sort_values(by=['Transaction_Date'])

Transaction_Description Transaction_Date  Amount
346                  Old Khaki       2020-04-01    3364
2662         Naartjie Clothing       2020-04-01    3286
2459         Guess Accessories       2020-04-01    1372
2675            Le Coq Sportif       2020-04-01     395
2393         The Cross Trainer       2020-04-01     505
...                        ...              ...     ...
2592        Fragrance Boutique       2021-03-31    2779
455   Browns The Diamond Store       2021-03-31    3726
2954                Sportscene       2021-03-31    3254
2172               Green Cross       2021-03-31     667
444                      Levis       2021-03-31    3011

[3200 rows x 3 columns]

In [12]:
# df1.merge(df2, left_on='lkey', right_on='rkey')
# Accdf.merge(transactdf)
df = Accdf.join(transactdf)

In [13]:
df

Name   Surname           City         accountId        cardNumber  \
0       Onyango   Kariuki        Midrand  1000394489162775  1040181015519329   
1          Felo   Motsepe      Zithobeni  1103826359325425  1057002793094764   
2     Fransisco    Akinyi    Krugersdorp  1083970301762132  1099635005048657   
3       Raphael    Wilson         Otukpo  1000116683622097  1100229865490051   
4          Felo   Viljoen        Lenasia  1012926937823961  1003073131310903   
...         ...       ...            ...               ...               ...   
3195      Caleb     Okeke          Gombe  1035472427678420  1092492790915671   
3196      Caleb     Okoro  Carletonville  1023284015180005  1062922367682775   
3197   Martinus  Macharia       Alagbado  1044729679865847  1019174574405382   
3198  Charmaine     Okoye       Pretoria  1091667027226529  1086746092412681   
3199      Emeka    Wilson          Dikwa  1089073164605702  1101171287917984   

     ActivationDate  Income    Transaction_Description Transaction_Date  \
0        2020-12-27   49326        Uchumi Supermarkets       2020-09-17   
1        2020-04-18   49457                    Mi-Vama       2020-06-16   
2        2021-03-22   14042                    Fabiani       2020-07-25   
3        2020-12-24   27502         Fragrance Boutique       2020-04-14   
4        2020-02-04    1321                      Levis       2020-12-19   
...             ...     ...                        ...              ...   
3195     2020-12-08   12325                      Kauai       2021-03-24   
3196     2021-01-21   22084                  Swarovski       2020-08-13   
3197     2021-02-07   59696                      Levis       2020-10-07   
3198     2020-07-30   55326                     Swatch       2020-09-30   
3199     2020-08-08   27797  Zoggy’s Tabacconist Store       2020-05-31   

      Amount  
0        752  
1       4515  
2       1166  
3       5967  
4        158  
...      ...  
3195    1322  
3196     711  
3197    3382  
3198     224  
3199    1254  

[3200 rows x 10 columns]

In [14]:
df['Transportation'] = df.Income * 0.23
df['Accounts'] = df.Income * 0.08
df['Grocery'] = df.Income * 0.09
df['Entertainment'] = df.Income * 0.03
df['Emergency'] = df.Income * 0.03
df['Housing'] = df.Income * 0.4
df['Budget'] = df['Accounts'] + df['Grocery'] +df['Entertainment'] + df['Emergency'] + df['Housing'] + df['Transportation']

In [15]:
df.round(2)

Name   Surname           City         accountId        cardNumber  \
0       Onyango   Kariuki        Midrand  1000394489162775  1040181015519329   
1          Felo   Motsepe      Zithobeni  1103826359325425  1057002793094764   
2     Fransisco    Akinyi    Krugersdorp  1083970301762132  1099635005048657   
3       Raphael    Wilson         Otukpo  1000116683622097  1100229865490051   
4          Felo   Viljoen        Lenasia  1012926937823961  1003073131310903   
...         ...       ...            ...               ...               ...   
3195      Caleb     Okeke          Gombe  1035472427678420  1092492790915671   
3196      Caleb     Okoro  Carletonville  1023284015180005  1062922367682775   
3197   Martinus  Macharia       Alagbado  1044729679865847  1019174574405382   
3198  Charmaine     Okoye       Pretoria  1091667027226529  1086746092412681   
3199      Emeka    Wilson          Dikwa  1089073164605702  1101171287917984   

     ActivationDate  Income    Transaction_Description Transaction_Date  \
0        2020-12-27   49326        Uchumi Supermarkets       2020-09-17   
1        2020-04-18   49457                    Mi-Vama       2020-06-16   
2        2021-03-22   14042                    Fabiani       2020-07-25   
3        2020-12-24   27502         Fragrance Boutique       2020-04-14   
4        2020-02-04    1321                      Levis       2020-12-19   
...             ...     ...                        ...              ...   
3195     2020-12-08   12325                      Kauai       2021-03-24   
3196     2021-01-21   22084                  Swarovski       2020-08-13   
3197     2021-02-07   59696                      Levis       2020-10-07   
3198     2020-07-30   55326                     Swatch       2020-09-30   
3199     2020-08-08   27797  Zoggy’s Tabacconist Store       2020-05-31   

      Amount  Transportation  Accounts  Grocery  Entertainment  Emergency  \
0        752        11344.98   3946.08  4439.34        1479.78    1479.78   
1       4515        11375.11   3956.56  4451.13        1483.71    1483.71   
2       1166         3229.66   1123.36  1263.78         421.26     421.26   
3       5967         6325.46   2200.16  2475.18         825.06     825.06   
4        158          303.83    105.68   118.89          39.63      39.63   
...      ...             ...       ...      ...            ...        ...   
3195    1322         2834.75    986.00  1109.25         369.75     369.75   
3196     711         5079.32   1766.72  1987.56         662.52     662.52   
3197    3382        13730.08   4775.68  5372.64        1790.88    1790.88   
3198     224        12724.98   4426.08  4979.34        1659.78    1659.78   
3199    1254         6393.31   2223.76  2501.73         833.91     833.91   

      Housing    Budget  
0     19730.4  42420.36  
1     19782.8  42533.02  
2      5616.8  12076.12  
3     11000.8  23651.72  
4       528.4   1136.06  
...       ...       ...  
3195   4930.0  10599.50  
3196   8833.6  18992.24  
3197  23878.4  51338.56  
3198  22130.4  47580.36  
3199  11118.8  23905.42  

[3200 rows x 17 columns]

In [16]:
df['RunningBalance'] = df['Budget'] - df['Income']

In [17]:
df

Name   Surname           City         accountId        cardNumber  \
0       Onyango   Kariuki        Midrand  1000394489162775  1040181015519329   
1          Felo   Motsepe      Zithobeni  1103826359325425  1057002793094764   
2     Fransisco    Akinyi    Krugersdorp  1083970301762132  1099635005048657   
3       Raphael    Wilson         Otukpo  1000116683622097  1100229865490051   
4          Felo   Viljoen        Lenasia  1012926937823961  1003073131310903   
...         ...       ...            ...               ...               ...   
3195      Caleb     Okeke          Gombe  1035472427678420  1092492790915671   
3196      Caleb     Okoro  Carletonville  1023284015180005  1062922367682775   
3197   Martinus  Macharia       Alagbado  1044729679865847  1019174574405382   
3198  Charmaine     Okoye       Pretoria  1091667027226529  1086746092412681   
3199      Emeka    Wilson          Dikwa  1089073164605702  1101171287917984   

     ActivationDate  Income    Transaction_Description Transaction_Date  \
0        2020-12-27   49326        Uchumi Supermarkets       2020-09-17   
1        2020-04-18   49457                    Mi-Vama       2020-06-16   
2        2021-03-22   14042                    Fabiani       2020-07-25   
3        2020-12-24   27502         Fragrance Boutique       2020-04-14   
4        2020-02-04    1321                      Levis       2020-12-19   
...             ...     ...                        ...              ...   
3195     2020-12-08   12325                      Kauai       2021-03-24   
3196     2021-01-21   22084                  Swarovski       2020-08-13   
3197     2021-02-07   59696                      Levis       2020-10-07   
3198     2020-07-30   55326                     Swatch       2020-09-30   
3199     2020-08-08   27797  Zoggy’s Tabacconist Store       2020-05-31   

      Amount  Transportation  Accounts  Grocery  Entertainment  Emergency  \
0        752        11344.98   3946.08  4439.34        1479.78    1479.78   
1       4515        11375.11   3956.56  4451.13        1483.71    1483.71   
2       1166         3229.66   1123.36  1263.78         421.26     421.26   
3       5967         6325.46   2200.16  2475.18         825.06     825.06   
4        158          303.83    105.68   118.89          39.63      39.63   
...      ...             ...       ...      ...            ...        ...   
3195    1322         2834.75    986.00  1109.25         369.75     369.75   
3196     711         5079.32   1766.72  1987.56         662.52     662.52   
3197    3382        13730.08   4775.68  5372.64        1790.88    1790.88   
3198     224        12724.98   4426.08  4979.34        1659.78    1659.78   
3199    1254         6393.31   2223.76  2501.73         833.91     833.91   

      Housing    Budget  RunningBalance  
0     19730.4  42420.36        -6905.64  
1     19782.8  42533.02        -6923.98  
2      5616.8  12076.12        -1965.88  
3     11000.8  23651.72        -3850.28  
4       528.4   1136.06         -184.94  
...       ...       ...             ...  
3195   4930.0  10599.50        -1725.50  
3196   8833.6  18992.24        -3091.76  
3197  23878.4  51338.56        -8357.44  
3198  22130.4  47580.36        -7745.64  
3199  11118.8  23905.42        -3891.58  

[3200 rows x 18 columns]

In [18]:
pd.Series(df['Transaction_Description']).str.replace('Earth', 'Andile', regex=True)

0             Uchumi Supermarkets
1                         Mi-Vama
2                         Fabiani
3              Fragrance Boutique
4                           Levis
                  ...            
3195                        Kauai
3196                    Swarovski
3197                        Levis
3198                       Swatch
3199    Zoggy’s Tabacconist Store
Name: Transaction_Description, Length: 3200, dtype: object